ZERO_YAW_LOW_BOUNDREY = -2
ZERO_YAW_HIGH_BOUNDERY = 2
NINETY_YAW_LOW_BOUNDREY = 88
NINETY_YAW_HIGH_BOUNDERY = 92
ONE_EIGHTY_YAW_LOW_BOUNDREY = 178
ONE_EIGHTY_YAW_HIGH_BOUNDERY = 182

# todo: not -1 1
TWO_HUNDRED_SEVENTY_YAW_LOW_BOUNDREY = -1
TWO_HUNDRED_SEVENTY_YAW_HIGH_BOUNDERY = 1

TURN_DIRECTION_RIGHT = 'right'
TURN_DIRECTION_LEFT = 'left'
TURN_DIRECTION_STRAIGHT = 'straight'


BASE_ROTATION = [0, 0, 0]

# Global variables for distance
FORWARD_DISTANCE_LEFT_TURN = 25
SIDE_DISTANCE_LEFT_TURN = 10

FORWARD_DISTANCE_RIGHT_TURN = 10
SIDE_DISTANCE_RIGHT_TURN = 10

FORWARD_DISTANCE_STRAIGHT = 20

TIME_TO_KEEP_STRAIGHT_AFTER_TURN = 5

DISTANCE_BEFORE_START_TURNING = 2.5


