

ZERO_YAW_LOW_BOUNDREY = -1
ZERO_YAW_HIGH_BOUNDERY = 1
NINETY_YAW_LOW_BOUNDREY = 89
NINETY_YAW_HIGH_BOUNDERY = 90
ONE_HUNDRED_EIGHTY_YAW_LOW_BOUNDREY = 179
ONE_HUNDRED_EIGHTY_YAW_HIGH_BOUNDERY = 181

TWO_HUNDRED_SEVENTY_YAW_LOW_BOUNDREY = -1
TWO_HUNDRED_SEVENTY_YAW_HIGH_BOUNDERY = 1

TURN_DIRECTION_RIGHT = 'right'
TURN_DIRECTION_LEFT = 'left'

BASE_ROTATION = [0, 0, 0]
