ZERO_YAW_LOW_BOUNDREY = -1
ZERO_YAW_HIGH_BOUNDERY = 1
NINETY_YAW_LOW_BOUNDREY = 89
NINETY_YAW_HIGH_BOUNDERY = 91
ONE_EIGHTY_YAW_LOW_BOUNDREY = 179
ONE_EIGHTY_YAW_HIGH_BOUNDERY = 181

# todo: not -1 1
TWO_HUNDRED_SEVENTY_YAW_LOW_BOUNDREY = -1
TWO_HUNDRED_SEVENTY_YAW_HIGH_BOUNDERY = 1

TURN_DIRECTION_RIGHT = 'right'
TURN_DIRECTION_LEFT = 'left'

BASE_ROTATION = [0, 0, 0]

# Global variables for distance
FORWARD_DISTANCE_LEFT_TURN = 20
SIDE_DISTANCE_LEFT_TURN = 10

FORWARD_DISTANCE_RIGHT_TURN = 10
SIDE_DISTANCE_RIGHT_TURN = 10

TIME_TO_KEEP_STRAIGHT_AFTER_TURN = 5

DISTANCE_BEFORE_START_TURNING = 2.5